const char *shaderShader = "#version 330 core\n"
	"in vec4 gl_FragCoord;\n"
	"out vec4 frag_color;\n"
	"#define MAX_ITERATIONS 500\n"
	"int get_iterations()\n"
	"{\n"
	" float real=(gl_FragCoord.x/1000.-.5)*4.;\n"
	" float imag=(gl_FragCoord.y/1000.-.375)*4.;\n"
	" \n"
	" int iterations=0;\n"
	" float const_real=real;\n"
	" float const_imag=imag;\n"
	" \n"
	" while(iterations<MAX_ITERATIONS)\n"
	" {\n"
	"   float tmp_real=real;\n"
	"   real=(real*real-imag*imag)+const_real;\n"
	"   imag=(2.*tmp_real*imag)+const_imag;\n"
	"   \n"
	"   float dist=real*real+imag*imag;\n"
	"   \n"
	"   if(dist>4.)\n"
	"   break;\n"
	"   \n"
	"   ++iterations;\n"
	" }\n"
	" return iterations;\n"
	"}\n"
	"vec3 gradient(float n){\n"
	" return vec3(3 * n / MAX_ITERATIONS, 3 * n / MAX_ITERATIONS - 1, 3 * n / MAX_ITERATIONS - 2)\n"
	"}\n"
	"vec4 return_color()\n"
	"{\n"
	" int iter=get_iterations();\n"
	" if(iter==MAX_ITERATIONS)\n"
	" {\n"
	"   gl_FragDepth=0.f;\n"
	"   return vec4(0.f,0.f,0.f,1.f);\n"
	" }\n"
	" \n"
	" float iterations=float(iter)/MAX_ITERATIONS;\n"
	" return vec4(gradient(iterations),1.f);\n"
	"}\n"
	"void main()\n"
	"{\n"
	" frag_color=return_color();\n"
	"}";
